core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from accounts.views import AccountLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', AccountLoginView.as_view()),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('projects.urls', 'projects'), namespace='projects')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path, include

from .views import (
    ProjectCreateView,
    ProjectDeleteView,
    ProjectDetailView,
    ProjectListView,
    ProjectUpdateView,
)

app_name = 'projects'

urlpatterns = [
    path('projects/', ProjectListView.as_view(), name='project-list'),
    path('projects/create/', ProjectCreateView.as_view(), name='project-create'),
    path('<str:project_slug>/', ProjectDetailView.as_view(), name='project-detail'),
    path('<str:project_slug>/update/', ProjectUpdateView.as_view(), name='project-update'),
    path('<str:project_slug>/delete/', ProjectDeleteView.as_view(), name='project-delete'),
    path('<str:project_slug>/', include(('jobs.urls', 'jobs'), namespace='jobs')),
]

projects/models.py
from django.db import models

from accounts.models import Account
from common.models import CommonSlugModel
from .managers import ProjectManager


class Project(CommonSlugModel):
    title = models.CharField(max_length=100, unique=True, verbose_name='Project Name')
    app_url = models.URLField(verbose_name='App URL')
    repository_url = models.URLField(verbose_name='Repository URL')
    team = models.ManyToManyField(Account, verbose_name='Team')

    objects = ProjectManager()

    class Meta:
        db_table = 'project'

    def __str__(self):
        return self.title

projects/forms.py
from django import forms

from .models import Project


class ProjectCreateModelForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = (
            'title',
            'app_url',
            'repository_url',
            'slug',
            'team',
        )
        widgets = {
            'team': forms.CheckboxSelectMultiple(
                attrs={'class': 'overflow-hidden h-32 text-red-500'}
            )
        }

projects/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import reverse
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView,
)

from .forms import ProjectCreateModelForm
from .models import Project


class ProjectListView(LoginRequiredMixin, ListView):
    template_name = 'projects/project-list.html'
    context_object_name = 'project_list'
    model = Project

    def get_queryset(self):
        queryset = Project.objects.all()
        search_query = self.request.GET.get('search')

        if search_query:
            queryset = Project.objects.filter(title__icontains=search_query)

        return queryset


class ProjectCreateView(LoginRequiredMixin, CreateView):
    template_name = 'projects/project-create.html'
    form_class = ProjectCreateModelForm

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('projects:project-list')


class ProjectDetailView(LoginRequiredMixin, DetailView):
    template_name = 'projects/project-detail.html'
    context_object_name = 'project'
    model = Project

    def get_object(self, *args, **kwargs):
        project_slug = self.kwargs.get('project_slug')

        return Project.objects.get(slug=project_slug)


class ProjectUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'projects/project-create.html'
    form_class = ProjectCreateModelForm

    def get_object(self):
        project_slug = self.kwargs.get('project_slug')

        return Project.objects.get(slug=project_slug)

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('projects:project-list')


class ProjectDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'projects/project-delete.html'

    def get_object(self):
        project_slug = self.kwargs.get('project_slug')

        return Project.objects.filter(slug=project_slug)

    def get_success_url(self):
        return reverse('projects:project-list')

projects/templates/projects/project-create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
    <div class="space-y-6">
        <div class="p-4 sm:rounded-lg sm:p-6 overflow-hidden">
            <div class="md:grid md:grid-cols-4 md:gap-6">
                <div class="md:col-span-1">
                    <h3 class="text-lg font-medium leading-6 text-gray-900">New Project</h3>
                </div>
                <div class="bg-white rounded-lg p-4 my-5 md:mt-0 md:col-span-2">
                    <form action="." method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" value="Save Project" class="text-gray-200 bg-blue-500 hover:bg-gray-700 flex-shrink-0 inline-flex items-center justify-center rounded-lg py-2 px-4" />
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

projects/templates/projects/project-delete.html
{% extends 'base.html' %}

{% block content %}
    <form action="." method="POST">{% csrf_token %}
        <h1>Are you sure you want to delete project "{{ object.title }}"?</h1>
        <p><input type="submit" value="Yes" /><a href="../">Cancel</a></p>
    </form>
{% endblock content %}

projects/templates/projects/project-detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="pb-5 sm:flex sm:items-center sm:justify-between">
        <h3 class="text-lg leading-6 font-medium text-gray-900">
            {{ project.title }}
        </h3>
        <div class="mt-3 sm:mt-0 sm:ml-4">
            <form method="GET" action="{% url 'projects:jobs:job-list' project.slug %}" class="relative flex items-center">
                <input type="text" name="search" id="search" placeholder="Search" class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full pr-12 sm:text-sm border-gray-300 rounded-l-md">
                <button class="-ml-px relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-r-md text-gray-700 bg-gray-50 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
                    {% include 'icons/heroicons/outline/search-circle.html' with height="h-5" width="w-5" view_box="0 0 24 24" %}
                </button>
            </form>
        </div>
    </div>
    <div>
        <div class="mb-5 hidden sm:block">
            <nav class="relative z-0 rounded-lg shadow flex divide-x divide-gray-200" aria-label="Tabs">
                <!-- Current: "text-gray-900", Default: "text-gray-500 hover:text-gray-700" -->
                <a href="#" class="text-gray-900 rounded-l-lg group relative min-w-0 flex-1 overflow-hidden bg-white py-4 px-4 text-sm font-medium text-center hover:bg-gray-50 focus:z-10" aria-current="page">
                    <span>Project</span>
                    <span aria-hidden="true" class="bg-indigo-500 absolute inset-x-0 bottom-0 h-0.5"></span>
                </a>
                <a href="#" class="text-gray-500 hover:text-gray-700 group relative min-w-0 flex-1 overflow-hidden bg-white py-4 px-4 text-sm font-medium text-center hover:bg-gray-50 focus:z-10">
                    <span>Team</span>
                    <span aria-hidden="true" class="bg-transparent absolute inset-x-0 bottom-0 h-0.5"></span>
                </a>
                <a href="{% url 'projects:jobs:job-list' project.slug %}" class="text-gray-500 hover:text-gray-700 rounded-r-lg group relative min-w-0 flex-1 overflow-hidden bg-white py-4 px-4 text-sm font-medium text-center hover:bg-gray-50 focus:z-10">
                    <span>Jobs</span>
                    <span aria-hidden="true" class="bg-transparent absolute inset-x-0 bottom-0 h-0.5"></span>
                </a>
            </nav>
        </div>
    </div>
    {% block project_jobs %}
    {% endblock project_jobs %}
{% endblock content %}

projects/templates/projects/project-form.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
    <div class="m-8 p-8 bg-gray-300 rounded-2xl shadow-xl">
        <div class="p-4 border-b border-gray-500 sm:px-6">
            <h3 class="text-2xl leading-6 font-medium text-gray-900">
                Create New Project
            </h3>
        </div>
        <div class="p-4">
            <form action="." method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Create Project" class="text-gray-200 bg-blue-500 hover:bg-gray-700 flex-shrink-0 inline-flex items-center justify-center rounded-lg py-2 px-4" />
            </form>
        </div>
    </div>
{% endblock content %}

projects/templates/projects/project-list-old.html
{% extends 'base.html' %}

{% block content %}
    <div class="pb-5 pt-2 pl-2 sm:flex sm:items-center sm:justify-between">
        <a href="{% url 'projects:project-create' %}" class="inline-flex items-center p-2 border border-transparent text-sm font-medium rounded-full shadow-lg text-white bg-cyan-600 hover:bg-cyan-700 hover:shadow-xl focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            <!-- Heroicon name: solid/plus -->
            <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd" />
            </svg>
        </a>
        <div class="mt-3 sm:mt-0 sm:ml-4">
            <form method="GET" action="{% url 'projects:project-list' %}" class="relative flex items-center">
                <input type="text" name="search" id="search" placeholder="Search" class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full pr-12 sm:text-sm border-gray-300 rounded-l-md">
                <button class="-ml-px relative inline-flex items-center space-x-2 px-4 py-2 border border-gray-300 text-sm font-medium rounded-r-md text-gray-700 bg-gray-50 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
                    {% include 'icons/heroicons/outline/search-circle.html' with height="h-5" width="w-5" view_box="0 0 24 24" %}
                </button>
            </form>
        </div>
    </div>
    {% if not project_list %}
        <div class="text-center">
            <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 13h6m-3-3v6m-9 1V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
            </svg>
            <h3 class="mt-2 text-sm font-medium text-gray-900">No Projects</h3>
            <p class="mt-1 text-sm text-gray-500">
                Get started by creating a new project.
            </p>
            <div class="mt-6">
                <a href="{% url 'projects:project-create' %}" class="inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    <!-- Heroicon name: solid/plus -->
                    <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd" />
                    </svg>
                    New Project
                </a>
            </div>
        </div>
    {% else %}
        {% for project in project_list %}
            <div class="bg-white shadow overflow-hidden sm:rounded-md">
                <ul class="divide-y divide-gray-200">
                    <li>
                        <a href="{% url 'projects:project-detail' project.slug %}" class="block hover:bg-gray-50">
    {#                    <a href="#" class="block hover:bg-gray-50">#}
                            <div class="px-4 py-4 flex items-center sm:px-6">
                                <div class="min-w-0 flex-1 sm:flex sm:items-center sm:justify-between">
                                    <div class="truncate">
                                        <div class="flex text-sm">
                                            <p class="font-medium text-indigo-600 truncate">{{ project.title }}</p>
                                        </div>
                                        <div class="mt-2 flex">
                                            <div class="flex items-center text-sm text-gray-500">
                                                <!-- Heroicon name: solid/calendar -->
                                                <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                                    <path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd" />
                                                </svg>
                                                <p>
                                                    Closing on
                                                    <time datetime="2020-01-07">January 7, 2020</time>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="mt-4 flex-shrink-0 sm:mt-0 sm:ml-5">
                                        <div class="flex overflow-hidden -space-x-1">
                                            {% for team_member in project.team.all %}
                                                <img class="inline-block h-6 w-6 rounded-full ring-2 ring-white" src="{{ team_member.profile.profile_picture.url }}" alt="{{ team_member.get_full_name }}">
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                                <div class="ml-5 flex-shrink-0">
                                    <!-- Heroicon name: solid/chevron-right -->
                                    <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                      <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                                    </svg>
                                </div>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="py-4">
        {% endfor %}
    {% endif %}
{% endblock content %}

projects/templates/projects/project-list.html
{% extends 'base.html' %}

{% block content %}
    <main class="flex-1 relative z-0 overflow-y-auto focus:outline-none xl:order-last">

        <div class="flex items-center justify-left pb-5 pl-5">
            <a href="{% url 'projects:project-create' %}" class="inline-flex items-center p-2 border border-transparent text-sm font-medium rounded-full shadow-lg text-white bg-cyan-600 hover:bg-cyan-700 hover:shadow-xl focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                <!-- Heroicon name: solid/plus -->
                <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd" />
                </svg>
            </a>
            <div class="px-6 pb-6">
                <form class="mt-6 flex space-x-4" action="#">
                    <div class="flex-1 min-w-0">
                        <label for="search" class="sr-only">Search</label>
                        <div class="relative rounded-md shadow-sm">
                            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                <!-- Heroicon name: solid/search -->
                                <svg class="h-5 w-5 text-gray-900 dark:text-gray-100" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                    <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
                                </svg>
                            </div>
                            <input type="search" name="search" id="search" class="bg-white dark:bg-black text-gray-900 dark:text-gray-100 border border-white dark:border-black w-full pl-10 text-sm rounded-lg shadow-lg" placeholder="Search">
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="flex justify-center items-center h-5/6">
            {% if not project_list %}

                <div class="text-center">
                    <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 13h6m-3-3v6m-9 1V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
                    </svg>
                    <h3 class="mt-2 text-sm font-medium text-gray-900">No Projects</h3>
                    <p class="mt-1 text-sm text-gray-500">
                        Get started by creating a new project.
                    </p>
                    <div class="mt-6">
                        <a href="{% url 'projects:project-create' %}" class="inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                            <!-- Heroicon name: solid/plus -->
                            <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                <path fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd" />
                            </svg>
                            New Project
                        </a>
                    </div>
                </div>

            {% else %}

                <ul class="space-y-6 w-3/5">
                    {% for project in project_list %}
                        <li class="transition duration-500 ease-in-out bg-white dark:bg-black transform hover:-translate-y-1 hover:scale-110 shadow-xl overflow-hidden rounded-xl">
                            <a href="{% url 'projects:project-detail' project.slug %}" class="px-6 py-4 block">
                                <div class="flex justify-between ml-3">
                                    <p class="text-sm font-medium text-gray-900 dark:text-gray-100">{{ project.title }}</p>
                                    <div class="mt-4 flex-shrink-0 sm:mt-0 sm:ml-5">
                                        <div class="flex overflow-hidden -space-x-1">
                                            {% for team_member in project.team.all %}
                                                <img class="inline-block h-6 w-6 rounded-full object-cover ring-2 ring-white dark:ring-black" src="{{ team_member.profile.profile_picture.url }}" alt="{{ team_member.get_full_name }}">
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                    {% endfor %}
                </ul>

            {% endif %}
        </div>
    </main>
{% endblock content %}