accounts/urls.py
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path

from .views import (
    AccountCreateView,
    AccountDeleteView,
    AccountDetailView,
    AccountListView,
    AccountUpdateView,
    AccountLoginView,
    AccountLogoutView,
)

urlpatterns = [
    path('', AccountListView.as_view(), name='account-list'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='account-create'),
    path('<str:username>/', AccountDetailView.as_view(), name='account-detail'),
    path('<str:username>/update/', AccountUpdateView.as_view(), name='account-update'),
    path('<str:username>/delete/', AccountDeleteView.as_view(), name='account-delete'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password-reset-done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password-reset-complete'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from accounts.views import AccountLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', AccountLoginView.as_view()),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('projects.urls', 'projects'), namespace='projects')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path, include

from .views import (
    ProjectCreateView,
    ProjectDeleteView,
    ProjectDetailView,
    ProjectListView,
    ProjectUpdateView,
)

app_name = 'projects'

urlpatterns = [
    path('projects/', ProjectListView.as_view(), name='project-list'),
    path('projects/create/', ProjectCreateView.as_view(), name='project-create'),
    path('<str:project_slug>/', ProjectDetailView.as_view(), name='project-detail'),
    path('<str:project_slug>/update/', ProjectUpdateView.as_view(), name='project-update'),
    path('<str:project_slug>/delete/', ProjectDeleteView.as_view(), name='project-delete'),
    path('<str:project_slug>/', include(('jobs.urls', 'jobs'), namespace='jobs')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" {% if user.profile.dark_mode %}class="dark"{% endif %}>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Testrix - A JTBD Manager</title>
        <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="https://use.typekit.net/vgo1zqc.css">
    </head>
    <body class="relative h-screen flex overflow-hidden bg-black font-acumin-pro-wide">
        <!-- Side Navbar -->
        {% if user.is_authenticated %}
            <div class="hidden lg:flex lg:flex-shrink-0">
                {% include 'navbar-side.html' %}
            </div>
        {% endif %}
        <!-- Main Section -->
        <div class="flex flex-col min-w-0 flex-1 bg-gray-100 dark:bg-true-gray-900 rounded-xl overflow-hidden">
            <div class="flex-1 relative z-0 flex overflow-hidden">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </body>
</html>

templates/navbar-side.html
{% load static %}

<div class="flex flex-col w-20">
    <div class="flex flex-col h-0 flex-1 place-content-between overflow-y-auto">

        <div class="flex items-center justify-center rounded-b-xl py-4">
            <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark.svg?color=white" alt="Site Logo">
        </div>

        <nav aria-label="Sidebar" class="py-6 flex flex-col items-center space-y-3">
            <a href="#" class="flex items-center p-4 rounded-lg text-white hover:bg-primary-700 {% if '/dashboard/' in request.path %}bg-primary-700{% endif %}">
                {% include 'icons/heroicons/outline/template-icon.html' %}
                <span class="sr-only">Dashboard</span>
            </a>
            <a href="{% url 'projects:project-list' %}" class="flex items-center p-4 rounded-lg text-white hover:bg-primary-700 {% if '/projects/' in request.path %}bg-primary-700{% endif %}">
                {% include 'icons/heroicons/outline/collection-icon.html' %}
                <span class="sr-only">Projects</span>
            </a>
            <a href="#" class="flex items-center p-4 rounded-lg text-white hover:bg-primary-700 {% if '/teams/' in request.path %}bg-primary-700{% endif %}">
                {% include 'icons/heroicons/outline/user-group-icon.html' %}
                <span class="sr-only">Teams</span>
            </a>
            {% if user.is_superuser %}
                <a href="{% url 'accounts:account-detail' user.username %}" class="flex items-center p-4 rounded-lg text-white hover:bg-primary-700 {% if '/accounts/' in request.path %}bg-primary-700{% endif %}">
                    {% include 'icons/heroicons/outline/users-icon.html' %}
                    <span class="sr-only">Users</span>
                </a>
            {% endif %}
        </nav>

        <div class="flex-shrink-0 py-4 flex items-center justify-center rounded-t-xl">
            <a href="#" class="flex-shrink-0 w-full">
                <img class="block mx-auto h-10 w-10 rounded-full object-cover" src="{{ user.profile.profile_picture.url }}" alt="">
                <div class="sr-only">
                    <p>
                        {{ user.get_full_name }}
                    </p>
                    <p>
                        Account settings
                    </p>
                </div>
            </a>
        </div>

    </div>
</div>

templates/navbar-top.html
{% load static %}

<nav class="bg-primary-900">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
            <div class="flex items-center">
                <form method="GET" action="{% url 'projects:project-list' %}" class="relative flex items-center">
                    <input type="text" name="search" id="search" placeholder="Search" class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full pr-12 sm:text-sm border-gray-300 rounded-l-md">
                    <button class="-ml-px relative inline-flex items-center space-x-2 px-4 py-2 border border-gray-300 text-sm font-medium rounded-r-md text-gray-700 bg-gray-50 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
                        {% include 'icons/heroicons/outline/search-circle.html' with height="h-5" width="w-5" view_box="0 0 24 24" %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</nav>

templates/new-page-template.html
{% extends 'base.html' %}

{% block content %}
    <!-- Right Column: Large Section -->
    <main class="flex-1 relative z-0 overflow-y-auto focus:outline-none xl:order-last">
    </main>
    <!-- Left Column: Small Section -->
    <aside class="hidden xl:order-first xl:flex xl:flex-col flex-shrink-0 w-96 border-r border-gray-200">
    </aside>
{% endblock content %}